version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6-browsers

    working_directory: ~/BaiduExporter

    branches:
      only:
        - master

    steps:
      - run: sudo apt update
      # add xxd dependency
      - run: sudo apt-get install -y vim-common
      - run: sudo apt-get install -y libpng-dev
      - checkout
      - restore_cache:
          keys:
            - node-chache-{{ .Branch }}-{{ checksum "chrome/package-lock.json" }}
      - run: npm --prefix chrome/ install
      - save_cache:
          key: node-chache-{{ .Branch }}-{{ checksum "chrome/package-lock.json" }}
          paths:
            - chrome/node_modules/
      - run: npm --prefix chrome/ run build
      - run: echo -e $KEY > /tmp/key.pem
      - run: .circleci/pack chrome/dist /tmp/key.pem
      - run: rm -rf chrome/release/
      - run: mv chrome/dist/ chrome/release/

      - run: |
          git config --global user.email "acgotaku311@gmail.com"
          git config --global user.name "acgotaku311"
          git add BaiduExporter.crx
          git add chrome/release/
          git commit -m "[ci skip] update chrome.crx and release"
          git push --set-upstream origin master
